[package]

name = "moby"
version = "0.2.0"
authors = ["Wojciech Kępka <wojciech@wkepka.dev"]
description = "Interface to Docker API"
documentation = "https://docs.rs/moby"
homepage = "https://github.com/wojciechkepka/moby"
repository = "https://github.com/wojciechkepka/moby"
keywords = ["docker", "unix", "containers", "api", "moby"]
license = "MIT"
edition = "2018"
readme = "README.md"

[dependencies]
base64 = "0.13"
byteorder = "1.4"
bytes = "1.0"
chrono = { version = "0.4", optional = true, features = ["serde"] }
flate2 = "1.0"
futures-util = "0.3"
futures_codec = "0.4"
hyper = { version = "0.14", features = ["client", "http1", "tcp", "stream"] }
hyper-openssl = { version = "0.9", optional = true }
hyperlocal = { version = "0.8", optional = true }
log = "0.4"
mime = "0.3"
openssl = { version = "0.10", optional = true }
pin-project = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4"
tokio = "1.0"
url = "2.1"
paste = "1"
thiserror = "1"


[dev-dependencies]
env_logger = "0.8"
# Required for examples to run
futures = "0.3.1"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[features]
default = ["chrono", "unix-socket", "tls"]
unix-socket = ["hyperlocal"]
tls = ["openssl", "hyper-openssl"]
vendored-ssl = ["tls", "openssl/vendored"]
